export const LOGIN_CHANGE_EMAIL_TEXT = 'LOGIN_CHANGE_EMAIL_TEXT';
export const LOGIN_CHANGE_PASSWORD_TEXT = 'LOGIN_CHANGE_PASSWORD_TEXT';
export const LOGIN_SET_EMAIL_ERROR = 'LOGIN_SET_EMAIL_ERROR';
export const LOGIN_SET_PASSWORD_ERROR = 'LOGIN_SET_PASSWORD_ERROR';
export const LOGIN_SET_IS_NO_REGISTER = 'LOGIN_SET_IS_NO_REGISTER';
export const LOGIN_SET_IS_AUTH_ERROR = 'LOGIN_SET_IS_AUTH_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_CHECK = 'USER_CHECK';
export const USER_LOGOUT = 'USER_LOGOUT';
