export const LOGIN_CHANGE_EMAIL_TEXT = 'LOGIN_CHANGE_EMAIL_TEXT';
export const LOGIN_CHANGE_PASSWORD_TEXT = 'LOGIN_CHANGE_PASSWORD_TEXT';
export const LOGIN_SET_EMAIL_ERROR = 'LOGIN_SET_EMAIL_ERROR';
export const LOGIN_SET_PASSWORD_ERROR = 'LOGIN_SET_PASSWORD_ERROR';
export const LOGIN_SET_IS_NO_REGISTER = 'LOGIN_SET_IS_NO_REGISTER';
export const LOGIN_SET_IS_AUTH_ERROR = 'LOGIN_SET_IS_AUTH_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_CHECK = 'USER_CHECK';
export const USER_LOGOUT = 'USER_LOGOUT';

export const REQUEST_ERROR_SET_ERROR = 'REQUEST_ERROR_SET_ERROR';
export const REQUEST_ERROR_UNSET_ERROR = 'REQUEST_ERROR_UNSET_ERROR';

export const ORDERS_SET_ORDERS = 'ORDERS_SET_ORDERS';
export const ORDERS_SET_VISIBLE_ORDERS = 'ORDERS_SET_FILTERED_ORDERS';

export const PAGINATION_SET_CURRENT_PAGE = 'PAGINATION_SET_ACTIVE_PAGE';
export const PAGINATION_SET_COUNT_PAGES = 'PAGINATION_SET_COUNT_PAGES';
export const PAGINATION_SET_NEXT_PAGE = 'PAGINATION_SET_NEXT_PAGE';
export const PAGINATION_SET_PREV_PAGE = 'PAGINATION_SET_PREV_PAGE';

export const ORDER_SET_ORDER = 'ORDER_SET_ORDER';
export const ORDER_SET_ADDITIONAL_OPTION = 'ORDER_SET_ADDITIONAL_OPTION';
export const ORDER_SET_OPTION = 'ORDER_SET_OPTION';

export const POPUP_SET_POPUP = 'POPUP_SET_POPUP';
export const POPUP_UNSET_POPUP = 'POPUP_UNSET_POPUP';

export const ENTITIES_SET_STATUSES = 'ENTITIES_SET_STATUSES';
export const ENTITIES_SET_CARS = 'ENTITIES_SET_CARS';
export const ENTITIES_SET_CITIES = 'ENTITIES_SET_CITIES';
export const ENTITIES_SET_POINTS = 'ENTITIES_SET_POINTS';
